services:
    postgres:
        image: postgres:17
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        networks:
            - internal
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    postgres_data:

networks:
    internal:
        driver: bridge
