services:
    postgres-test:
        image: postgres:16-alpine
        container_name: amai-test-db
        environment:
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
            POSTGRES_DB: amai_test
            POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
        ports:
            - "5433:5432"
        volumes:
            - postgres_test_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test_user -d amai_test"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - test-network

volumes:
    postgres_test_data:
        driver: local

networks:
    test-network:
        driver: bridge
